// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eykbshtvjfvkpwhsvzvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5a2JzaHR2amZ2a3B3aHN2enZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NTY4NTgsImV4cCI6MjA4NDQzMjg1OH0.V0j6evMFhgdS4NWG7ublffqu3hlmbofRSgNZZEU1rEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});